### PR TITLE
Continuous Integration (w/ Travis CI)

### PR DESCRIPTION
**Pull request by groue**

### CODE REVIEW

**Comment by groue** [comment]
@RxSwiftCommunity/contributors, is one of you able to give me admin rights on https://travis-ci.org/RxSwiftCommunity/RxGRDB?

Travis tells me to contact "the admin", but won't tell anywhere who this is.

> *This is not an active repository*
> 
> You don't have sufficient rights to enable this repo on Travis. 
>
> Please contact the admin to enable it or to receive admin rights yourself.

On a side note, this is a new use case related to https://github.com/RxSwiftCommunity/contributors/issues/27

**Comment by freak4pc** [comment]
I just manual triggered a build and it seems fine 🤔 
Where are you seeing that message? 

https://travis-ci.org/RxSwiftCommunity/RxGRDB/builds/295831458

**Comment by fpillet** [comment]
I activated the repo

**Comment by fpillet** [comment]
Not sure about Travis, let me see if there's something I can do with access rights

**Comment by ashfurrow** [comment]
FYI we've been granted access to Circle's CI platform, in case anyone'd like to try them out.

**Comment by groue** [comment]
Thanks @fpillet ! @freak4pc, I guess you've been caught in a race condition ;-)

Thanks for the access, @ashfurrow. I'll be able to deal with mundane Travis tasks myself in the future 👍

**Comment by freak4pc** [comment]
@ashfurrow Has access to Circle CI actually, so I believe florent gave you repo access :)

**Comment by fpillet** [comment]
No in fact I just "activated" the repo on Travis, there was a button for this. Not sure why I'd have the rights and Gwendal wouldn't, though.

**Comment by groue** [comment]
I'm not admin yet, because I can't disable RxSwiftCommunity/RxGRDB at https://travis-ci.org/profile/RxSwiftCommunity?offset=25. I also understand now that this would allow me to disable Travis on other RxSwiftCommunity repos as well: this is not a privilege I want to claim.

So I think we're all set now. Thank you very much Ash, Florent, Shai :-)

**Comment by fpillet** [comment]
Okay I have community admin rights, that's why I could activate your repo. I think that unless you're listed as "Owner" in RxSwiftCommunity you're not allowed to touch the repo activation flags on Travis. Makes sense.

**Pull request merged**
