### PR TITLE
Documentation improvements

### PR DESCRIPTION
**Pull request by groue**
Hello,

This PR improves documentation with explicit requirements, installation method, general library usage, and more precise description of the features.

### CODE REVIEW

**Comment by groue** [comment]
@freak4pc I'm not used yet to the RxSwiftCommunity practices: I've got no problem gathering changes in cohesive PRs, but I did not understand if you intend each PR to be peer-reviewed (in which case somebody should watch this repo or I'll have to beg for attention each time I want to maintain it). Merging this one for now.

**Comment by freak4pc** [comment]
I'm no authority on this but I imagine since you're the maintainer, you can merge your own changes :) Reviews should be by you & community for other people's changes, I imagine.

**Comment by groue** [comment]
All right, I can do that! I guess I feel at home now - thanks!

**Comment by freak4pc** [comment]
Feel right at home, this is eventually still your own project! Just
maintained with the help of the community hopefully :) 🤘

-- 
Shai Mishali

**Pull request merged**
