### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by gre4ixin**
Update Swift version badge in README file

### CODE REVIEW

**Comment by groue** [comment]
Hello @gre4ixin, thanks for your pull request.

RxGRDB requires Swift 4.1+, and supports Swift 4.2. I used to focus on the requirement side, and put a 4.1 badge. Is there a reason you want to change this?

**Comment by gre4ixin** [comment]
@groue I apologize, I saw that version 0.12.0 is compatible with swift 4.2, and in badge swift 4.1 is specified and thought that you forgot to specify it the actual version)

**Comment by groue** [comment]
Maybe we could even remove the badge: this would end of the ambiguity for good.

**Comment by groue** [comment]
OK. Maybe I'll address this badge "issue" in the next release. Please reopen if you wish to further discuss this topic.

**Pull request closed without merging**
